name : First Workflow
on : [push]

jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline command
        run: |
           echo "node verions is being printed"
           node -v
           npm -v